### PR TITLE
Different badge ribbons

### PR DESCRIPTION
**Pull request by Douile**
Added a different badge ribbon for each level of achievement.

### CODE REVIEW

**Comment by Chew** [comment]
Is the bot on the server these emotes are on?

**Comment by Douile** [comment]
Yes, it is. I believe all bots have nitro so it should work.

**Comment by Chew** [comment]
Yes it will, I'll check this out later

**Comment by Chew** [comment]
My editor doesn't want me to checkout your changes, so once it's fixed, we'll come back to this.

**Comment by Douile** [comment]
@Chewsterchew ok, nice
Hopefully they fix fast

**Comment by Chew** [comment]
Finally got around to checking this out, unfortunately the emojis don't seem to work. Is the bot on the same server as the Emojis?

**Pull request closed without merging**
